import { readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";
const read = (path) => readFile(new URL(path, import.meta.url), "utf8");
test("React entry owns the generated runtime", async () => { const [html, main, app] = await Promise.all([read("../src/index.html"), read("../src/main.tsx"), read("../src/app/App.tsx")]); assert.match(html, /id="root"/); assert.match(html, /main\.tsx/); assert.doesNotMatch(html, /welcome\.js|post-signin\.js/); assert.match(main, /<App \/>/); assert.match(app, /createTauriGateway/); });
test("typed gateway allowlists current Rust commands and safe argument shapes", async () => { const source = await read("../src/platform/tauri/gateway.ts"); for (const command of ["sign_in", "complete_new_password", "restore_session", "sign_out", "list_children", "get_usage", "mount_status", "mount_stash", "unmount_stash"]) assert.match(source, new RegExp(`\\"${command}\\"`)); assert.match(source, /folderId/); assert.match(source, /newPassword/); assert.match(source, /remember/); assert.doesNotMatch(source, /fetch|XMLHttpRequest|localStorage|sessionStorage/); });
test("auth machine keeps the temporary-password challenge outside React state and props", async () => { const [machine, welcome, types, gateway] = await Promise.all([read("../src/state/authMachine.ts"), read("../src/components/WelcomeScreen.tsx"), read("../src/domain/types.ts"), read("../src/platform/tauri/gateway.ts")]); assert.match(machine, /NEW_PASSWORD_REQUIRED/); assert.match(machine, /remember: boolean/); assert.doesNotMatch(machine, /session/); assert.doesNotMatch(types, /session/); assert.match(welcome, /completeNewPassword\(state\.username, next, state\.remember\)/); assert.doesNotMatch(welcome, /state\.session|session:/); assert.match(gateway, /pendingNewPasswordSession/); assert.doesNotMatch(welcome, /localStorage|sessionStorage/); });
test("Files preserves entity distinction, hierarchy navigation, states, and sorting", async () => { const source = await read("../src/components/FilesScreen.tsx"); for (const marker of ["listChildren", "Loading your STASH", "This folder is empty", "couldn't load this folder", "Folder", "File", "folderId", "originalRelativePath", "toggleSort"]) assert.match(source, new RegExp(marker)); assert.match(source, /setPath\(\(current\) => \[\.\.\.current/); assert.doesNotMatch(source, /checksum|presigned|objectKey/); });
test("shell includes approved labels, planned states, theme/focus/responsive/reduced-motion behavior", async () => { const [shell, rail, css] = await Promise.all([read("../src/components/Shell.tsx"), read("../src/components/NavigationRail.tsx"), read("../src/styles.css")]); for (const label of ["Home", "Files", "Search", "Recent Stashes", "Offline", "Transfers", "Settings"]) assert.match(rail, new RegExp(label)); assert.match(rail, /\+ Stash it/); assert.match(rail, /Search your STASH/); assert.match(shell, /planned for a later STASH capability/); assert.match(shell, /Storage unavailable/); assert.match(shell, /Mount unavailable/); assert.match(rail, /onRetryMount/); assert.doesNotMatch(shell, /window\.alert/); assert.doesNotMatch(rail, /window\.alert/); assert.match(css, /prefers-color-scheme: dark/); assert.match(css, /prefers-reduced-motion: reduce/); assert.match(css, /focus-visible/); assert.match(css, /max-width: 760px/); });

test("Files uses explicit typed online/stale/offline/unavailable capability states", async () => { const [types, files, shell] = await Promise.all([read("../src/domain/types.ts"), read("../src/components/FilesScreen.tsx"), read("../src/components/Shell.tsx")]); for (const state of ["offline", "stale", "unavailable"]) assert.match(types, new RegExp(state)); assert.match(files, /CapabilityState<ChildItem\[\]>/); assert.match(files, /Data may be stale/); assert.match(shell, /Offline view is not available in this build yet/); });

test("generated distribution includes the imported application stylesheet when built", async (context) => {
  let generated;
  try { generated = await read("../dist/index.html"); } catch (error) { if (error?.code === "ENOENT") { context.skip("run npm run build for generated-entry parity"); return; } throw error; }
  assert.match(generated, /assets\/index-[^\"]+\.css/);
});
